import localFont from "next/font/local";
import { Analytics } from "@vercel/analytics/react";  // Import Vercel Analytics
import "./globals.css";

const DMSans_Reg = localFont({
  src: "./fonts/DMSans_18pt-Regular.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${DMSans_Reg.variable} ${DMSans_Reg.variable} antialiased`}>
        {children}

        {/* Add Analytics component here to enable analytics tracking */}
        <Analytics />
      </body>
    </html>
  );
}