import localFont from "next/font/local";
import "./globals.css";

const DMSans_Reg = localFont({
  src: "./fonts/DMSans_18pt-Regular.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${DMSans_Reg.variable} ${DMSans_Reg.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
